services:
  db:
    image: postgres:15-alpine
    container_name: trailmix-postgres
    environment:
      POSTGRES_DB: trailmix
      POSTGRES_USER: trailmix
      POSTGRES_PASSWORD: trailmix
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trailmix -d trailmix"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    command: >
      postgres
      -c log_statement=all
      -c log_destination=stderr
      -c logging_collector=on
      -c log_min_messages=info

volumes:
  postgres_data:
